version: '3.7'
services:
  vue-reader-simulator:
    image: vuereadersimulator
    build: .
    restart: always
    networks:
      - gateway
    ports:
      - 8085:8085
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    networks:
      - gateway
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
networks:
  gateway:
    driver: bridge
