version: '3.7'
services:
  vue-reader-simulator:
    image: vuereadersimulator
    build: .
    restart: always
    networks:
      - gateway
    ports:
      - 8085:8085
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.1
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    networks:
      - gateway
    volumes:
      - mongodata:/data/db
      - mongodata:/var/log/mongodb
      - mongodata:/docker-entrypoint-initdb.d/
networks:
  gateway:
    driver: bridge
volumes:
  mongodata:
  

